// <auto-generated />
using System;
using Alpha.Pesagem.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Api.Pesagem.Migrations
{
    [DbContext(typeof(AlphaDbContext))]
    partial class AlphaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Alpha.Pesagem.Api.Models.Fazenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short>("Inativo")
                        .HasColumnType("smallint");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.ToTable("Fazendas");
                });

            modelBuilder.Entity("Alpha.Pesagem.Api.Models.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apelido")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Aviso")
                        .HasColumnType("text");

                    b.Property<string>("Bairro")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Bloqueado")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("Celular")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<int?>("CodigoIbgeCidade")
                        .HasColumnType("integer");

                    b.Property<string>("Complemento")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Contato")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("FazendaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("IdAlphaExpress")
                        .HasColumnType("integer");

                    b.Property<string>("Inativo")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("NomeRazao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<short>("Sincronizado")
                        .HasColumnType("smallint");

                    b.Property<string>("Telefone")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<short>("TipoPessoa")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("UsuarioAlteracaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Vendedores")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FazendaId");

                    b.HasIndex("UsuarioAlteracaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("Alpha.Pesagem.Api.Models.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("FazendaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("IdAlphaExpress")
                        .HasColumnType("integer");

                    b.Property<string>("Mensagem")
                        .HasColumnType("text");

                    b.Property<Guid?>("UsuarioAlteracaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FazendaId");

                    b.HasIndex("UsuarioAlteracaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("Alpha.Pesagem.Api.Models.Peso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brinco")
                        .HasColumnType("text");

                    b.Property<string>("BrincoEletronico")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FazendaId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FazendaId1")
                        .HasColumnType("uuid");

                    b.Property<int?>("IdAlphaExpress")
                        .HasColumnType("integer");

                    b.Property<string>("Idade")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("PesoTotal")
                        .HasColumnType("text");

                    b.Property<string>("Raca")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.Property<short>("Sincronizado")
                        .HasColumnType("smallint");

                    b.Property<string>("ValorMedio")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FazendaId");

                    b.HasIndex("FazendaId1");

                    b.ToTable("Peso");
                });

            modelBuilder.Entity("Alpha.Pesagem.Api.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("FazendaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("IdAlphaExpress")
                        .HasColumnType("integer");

                    b.Property<short>("Inativo")
                        .HasColumnType("smallint");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Salto")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Senha")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("FazendaId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Alpha.Pesagem.Api.Models.Fornecedor", b =>
                {
                    b.HasOne("Alpha.Pesagem.Api.Models.Fazenda", "Fazenda")
                        .WithMany()
                        .HasForeignKey("FazendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Alpha.Pesagem.Api.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("UsuarioAlteracaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Alpha.Pesagem.Api.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Fazenda");

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("Alpha.Pesagem.Api.Models.Log", b =>
                {
                    b.HasOne("Alpha.Pesagem.Api.Models.Fazenda", "Fazenda")
                        .WithMany()
                        .HasForeignKey("FazendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Alpha.Pesagem.Api.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("UsuarioAlteracaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Alpha.Pesagem.Api.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Fazenda");

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("Alpha.Pesagem.Api.Models.Peso", b =>
                {
                    b.HasOne("Alpha.Pesagem.Api.Models.Fazenda", "Fazenda")
                        .WithMany()
                        .HasForeignKey("FazendaId1");

                    b.Navigation("Fazenda");
                });

            modelBuilder.Entity("Alpha.Pesagem.Api.Usuario", b =>
                {
                    b.HasOne("Alpha.Pesagem.Api.Models.Fazenda", "Fazenda")
                        .WithMany()
                        .HasForeignKey("FazendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fazenda");
                });
#pragma warning restore 612, 618
        }
    }
}
